FROM python:3

RUN python -m pip install pymongo
RUN python -m pip install grpcio
RUN python -m pip install msgpack-python
RUN python -m pip install fluent-logger

COPY master.py /opt/scheduler/
COPY masterslave_pb2.py /opt/scheduler/
COPY masterslave_pb2_grpc.py /opt/scheduler


