# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import masterslave_pb2 as masterslave__pb2


class TaskSchedulerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Join = channel.unary_unary(
        '/TaskScheduler/Join',
        request_serializer=masterslave__pb2.JoinRequest.SerializeToString,
        response_deserializer=masterslave__pb2.JoinResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/TaskScheduler/Heartbeat',
        request_serializer=masterslave__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=masterslave__pb2.HeartbeatResponse.FromString,
        )
    self.Task = channel.unary_unary(
        '/TaskScheduler/Task',
        request_serializer=masterslave__pb2.TaskRequest.SerializeToString,
        response_deserializer=masterslave__pb2.TaskResponse.FromString,
        )
    self.Status = channel.unary_unary(
        '/TaskScheduler/Status',
        request_serializer=masterslave__pb2.StatusRequest.SerializeToString,
        response_deserializer=masterslave__pb2.StatusResponse.FromString,
        )
    self.AfterMasterFailure = channel.unary_unary(
        '/TaskScheduler/AfterMasterFailure',
        request_serializer=masterslave__pb2.AfterMasterFailureRequest.SerializeToString,
        response_deserializer=masterslave__pb2.AfterMasterFailureResponse.FromString,
        )
    self.Acknowledge = channel.unary_unary(
        '/TaskScheduler/Acknowledge',
        request_serializer=masterslave__pb2.AcknowledgeRequest.SerializeToString,
        response_deserializer=masterslave__pb2.AcknowledgeResponse.FromString,
        )


class TaskSchedulerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Join(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Task(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AfterMasterFailure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Acknowledge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaskSchedulerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Join': grpc.unary_unary_rpc_method_handler(
          servicer.Join,
          request_deserializer=masterslave__pb2.JoinRequest.FromString,
          response_serializer=masterslave__pb2.JoinResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=masterslave__pb2.HeartbeatRequest.FromString,
          response_serializer=masterslave__pb2.HeartbeatResponse.SerializeToString,
      ),
      'Task': grpc.unary_unary_rpc_method_handler(
          servicer.Task,
          request_deserializer=masterslave__pb2.TaskRequest.FromString,
          response_serializer=masterslave__pb2.TaskResponse.SerializeToString,
      ),
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=masterslave__pb2.StatusRequest.FromString,
          response_serializer=masterslave__pb2.StatusResponse.SerializeToString,
      ),
      'AfterMasterFailure': grpc.unary_unary_rpc_method_handler(
          servicer.AfterMasterFailure,
          request_deserializer=masterslave__pb2.AfterMasterFailureRequest.FromString,
          response_serializer=masterslave__pb2.AfterMasterFailureResponse.SerializeToString,
      ),
      'Acknowledge': grpc.unary_unary_rpc_method_handler(
          servicer.Acknowledge,
          request_deserializer=masterslave__pb2.AcknowledgeRequest.FromString,
          response_serializer=masterslave__pb2.AcknowledgeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TaskScheduler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
